version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: ./gradlew clean
      - run: ./gradlew build
      - run: ./gradlew assembleDebug
      - run:
         name: Deploy to hockey app
         command: sh ./deploy_dev.sh