version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: cd ..
      - run: ./gradlew bumperVersionPatch
      - run: git config --global credential.helper cache
      - run: git push https://ec19ba62c5bf458ff503ea4dcf5bd354dcf5a270@github.com/gumenza01/test-circle-ci.git master
      - run: ./gradlew clean
      - run: ./gradlew build
      - run: ./gradlew assembleDebug
      - run: sh deploy_dev.sh
    branches:
      only:
        - master