version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: cd ..
      - run: ./gradlew bumperVersionPatch
      - run: git push --set-upstream origin ${CIRCLE_BRANCH}
      - run: ./gradlew clean
      - run: ./gradlew build
      - run: ./gradlew assembleDebug
      - run: sh deploy_dev.sh
    branches:
      only:
        - master