version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run: ./gradlew clean
      - run: ./gradlew build
      - run: ./gradlew assembleDebug
      - run: sh ./deploy_dev.sh